version: "2.0"

services:
  discord-bot:
    image: your-docker-image-name:latest
    env:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - COMMAND_PREFIX=${COMMAND_PREFIX}
      - DATABASE_PATH=/data/database.db
      - REPORTS_DIR=/data/reports
      - LOG_LEVEL=${LOG_LEVEL}
      - ADMIN_USER_IDS=${ADMIN_USER_IDS}
      - XAI_API_KEY=${XAI_API_KEY}
      - BACKUP_CHANNEL_ID=${BACKUP_CHANNEL_ID}
      - BACKUP_INTERVAL_HOURS=${BACKUP_INTERVAL_HOURS}
      - BACKUP_RETENTION_DAYS=${BACKUP_RETENTION_DAYS}
      - HEALTH_CHECK_INTERVAL_MINUTES=${HEALTH_CHECK_INTERVAL_MINUTES}
      - ERROR_THRESHOLD=${ERROR_THRESHOLD}
      - ADMIN_NOTIFICATION_CHANNEL_ID=${ADMIN_NOTIFICATION_CHANNEL_ID}
      - BACKUP_CLOUD_PROVIDER=${BACKUP_CLOUD_PROVIDER}
      - BACKUP_COMPRESSION_LEVEL=${BACKUP_COMPRESSION_LEVEL}
      - BACKUP_VERIFY_INTEGRITY=${BACKUP_VERIFY_INTEGRITY}
      - BACKUP_ROTATION_SCHEME=${BACKUP_ROTATION_SCHEME}
      - BACKUP_ENCRYPTION_KEY=${BACKUP_ENCRYPTION_KEY}
      - SENTRY_DSN=${SENTRY_DSN}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    expose:
      - port: 80
        as: 80
        to:
          - global: true
    resources:
      cpu:
        units: 0.5
      memory:
        size: 1Gi
      storage:
        - size: 5Gi
          mount: /data
          
profiles:
  compute:
    discord-bot:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 1Gi
        storage:
          - size: 5Gi
            name: data
            
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        discord-bot:
          denom: uakt
          amount: 100

deployment:
  discord-bot:
    dcloud:
      profile: discord-bot
      count: 1